import { readFile, readdir, writeFile } from 'node:fs/promises';
import { basename, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

function text(value, field) {
  if (typeof value !== 'string' || !value.trim() || value.includes('\0')) throw new Error(`Missing or invalid ${field}`);
}
function sourceUrl(value) {
  text(value, 'source URL');
  if (new URL(value).protocol !== 'https:') throw new Error('Nutrition sources must use HTTPS');
}
export function validateCatalog(catalog) {
  if (!catalog || typeof catalog !== 'object') throw new Error('Invalid catalog');
  text(catalog.chain, 'chain'); sourceUrl(catalog.sourceUrl);
  if (!/^\d{4}-\d{2}-\d{2}$/.test(catalog.retrievedAt)) throw new Error('Missing retrieval date');
  if (catalog.sourceKind && !['database', 'restaurant'].includes(catalog.sourceKind)) throw new Error('Invalid source kind');
  if (!Array.isArray(catalog.foods) || !catalog.foods.length) throw new Error('Empty menu');
  const ids = new Set();
  for (const food of catalog.foods) {
    text(food.id, 'food id'); text(food.name, 'food name'); text(food.servingLabel, 'serving description');
    if (ids.has(food.id)) throw new Error(`Duplicate food id: ${food.id}`);
    ids.add(food.id);
    for (const key of ['calories', 'protein', 'carbs', 'fat']) {
      if (typeof food[key] !== 'number' || !Number.isFinite(food[key]) || food[key] < 0) throw new Error(`Invalid ${key}: ${food.id}`);
    }
    if (food.servingGrams !== undefined && food.servingGrams !== null && (typeof food.servingGrams !== 'number' || !Number.isFinite(food.servingGrams) || food.servingGrams <= 0)) throw new Error(`Invalid weight: ${food.id}`);
    if (food.sourceUrl) sourceUrl(food.sourceUrl);
  }
  return catalog;
}
function sqlValue(value) { return value === undefined || value === null ? 'NULL' : typeof value === 'number' ? String(value) : `'${String(value).replaceAll("'", "''")}'`; }
export function catalogSql(slug, value) {
  if (!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(slug)) throw new Error('Invalid catalog slug');
  const catalog = validateCatalog(value);
  const source = catalog.source || (catalog.sourceKind === 'database' ? 'Nutrition database' : 'Official restaurant nutrition');
  const rows = catalog.foods.map(food => [
    `restaurant-${slug}-${food.id}`, food.name, catalog.chain, source, catalog.sourceKind || 'restaurant', food.sourceUrl || catalog.sourceUrl,
    1, 'serving', food.servingGrams, food.servingLabel, food.calories, food.protein, food.carbs, food.fat, catalog.retrievedAt, catalog.retrievedAt,
  ].map(sqlValue).join(','));
  const chunks = [];
  for (let i = 0; i < rows.length; i += 100) {
    chunks.push(`INSERT INTO foods (id,name,brand,source,source_kind,source_url,verified,nutrition_basis,serving_grams,serving_label,calories,protein,carbs,fat,checked_at,created_at) VALUES\n(${rows.slice(i, i + 100).join('),\n(')})\nON CONFLICT(id) DO UPDATE SET name=excluded.name,brand=excluded.brand,source=excluded.source,source_kind=excluded.source_kind,source_url=excluded.source_url,verified=excluded.verified,nutrition_basis=excluded.nutrition_basis,serving_grams=excluded.serving_grams,serving_label=excluded.serving_label,calories=excluded.calories,protein=excluded.protein,carbs=excluded.carbs,fat=excluded.fat,checked_at=excluded.checked_at;`);
  }
  return chunks.join('\n--> statement-breakpoint\n');
}

async function main() {
  const directory = resolve('data/restaurant-foods');
  const coverage = JSON.parse(await readFile('docs/restaurant-import/coverage.json', 'utf8'));
  const eligible = new Map();
  for (const chain of coverage.chains) {
    if (/excluded|outside|closed/.test(chain.eligibilityStatus ?? '')) continue;
    if (!chain.locations.some(location => location.distanceMiles !== null && location.distanceMiles !== undefined && location.distanceMiles <= 10)) continue;
    if (chain.catalogFile) eligible.set(basename(chain.catalogFile), chain);
    eligible.set(`${chain.slug}.json`, chain);
  }
  const sql = ['-- Generated by scripts/restaurant-catalog.mjs. Published per-serving nutrition; see source manifests.'];
  const imported = [], excluded = [];
  for (const file of (await readdir(directory)).filter(file => file.endsWith('.json')).sort()) {
    const catalog = validateCatalog(JSON.parse(await readFile(resolve(directory, file), 'utf8')));
    const chain = eligible.get(file);
    if (!chain) { excluded.push({ file, chain: catalog.chain, reason: 'No matched in-radius location evidence in coverage.json' }); continue; }
    sql.push(catalogSql(basename(file, '.json'), catalog));
    imported.push({ file, chain: catalog.chain, inventorySlug: chain.slug, eligibilityStatus: chain.eligibilityStatus, foodCount: catalog.foods.length, sourceUrl: catalog.sourceUrl, source: catalog.source || 'Official restaurant nutrition', sourceDate: catalog.sourceDate ?? null, retrievedAt: catalog.retrievedAt });
  }
  if (!imported.length) throw new Error('No eligible catalogs; audit location coverage before generating seeds');
  await writeFile('drizzle/0003_restaurant_catalog.sql', `${sql.join('\n--> statement-breakpoint\n')}\n`);
  const result = { zip: coverage.zip, radiusMiles: coverage.radiusMiles, center: coverage.center, generatedFrom: 'data/restaurant-foods + docs/restaurant-import/coverage.json', catalogCount: imported.length, foodCount: imported.reduce((sum, chain) => sum + chain.foodCount, 0), imported, excluded };
  await writeFile('docs/restaurant-import/import-summary.json', `${JSON.stringify(result, null, 2)}\n`);
  console.log(`Prepared ${result.foodCount} foods across ${result.catalogCount} chain catalogs; ${excluded.length} catalogs excluded pending location evidence.`);
}
if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) await main();
